name: Feature Workflow pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  # code-scan: # job that will scan code for linting errors
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repo code
  #       uses: actions/checkout@v2

  #     - name: Run Lint code
  #       uses: github/super-linter@v4
  #       continue-on-error: true
  #       env:
  #         DEFAULT_BRANCH: main
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         FILTER_REGEX_EXCLUDE: "^dist/.*"

  unit-tests: # job that will run unit tests
    runs-on: ubuntu-latest
    needs: code-scan

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23.7.0"

      - name: Run unit tests
        run: npm run test

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: "${{ github.workspace }}/test-report.html"
          retention-days: 2

  # build: # job that will build the project
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repo code
  #       uses: actions/checkout@v2

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "23.7.0"

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build with Parcel
  #       run: npm run build

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: kids-app
          # path: "${{ github.workspace }}/dist/"

