name: Feature Workflow pipeline

on:
  push: # when a push to any branch
    branches:
      - "**"
  pull_request: # when a PR is created/change
    branches:
      - main

jobs:
  # code-scan: # job that will scan code for linting errors
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repo code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0

  #     - name: Run Lint code
  #       uses: github/super-linter@latest
  #       continue-on-error: true
  #       env:
  #         DEFAULT_BRANCH: main
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         FILTER_REGEX_EXCLUDE: "^dist/.*"

  unit-tests: # job that will run unit tests
    runs-on: ubuntu-latest
    # needs: code-scan

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23.7.0"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: "${{ github.workspace }}/test-report.html"
          retention-days: 2

  build: # job that will build the project
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23.7.0"

      - name: Install dependencies
        run: npm install

      - name: Build with Parcel
        run: npm run build-app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kids-app
          path: "${{ github.workspace }}/dist/"

  deploy: # job that will deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23.7.0"

      - name: Install dependencies
        run: npm install

      - name: Set git user
        run: |
          git config --global user.name "johanna33"
          git config --global user.email "joha_17@hotmail.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          npm run deploy

      - name: Verify gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          ls -la
