name: Staging Workflow pipeline # pre-prod environment

on:
  push: # when PR is merge to main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.7.0"

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Build with Parcel
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kids-app
          path: "${{ github.workspace }}/dist/"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23.7.0"

      - name: Restore node_modules from cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: kids-app
          path: "${{ github.workspace }}/dist/"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          NODE_DEBUG=gh-pages npm run deploy

      - name: Verify gh-pages branch content
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          ls -la

# test (ui-api) job

# reports jobs,
